# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
  provider "aws" {
    region = "eu-central-1"
    shared_credentials_files = ["/Users/nahuel.cassinari/.aws/credentials"]
    profile = "sandbox"
  }
