# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "test-s3bucket-20221025163109283700000001"
    key     = "ex4/test/terraform.tfstate"
    profile = "sandbox"
    region  = "eu-central-1"
  }
}
